/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWebsiteAnalysisRouteImport } from './routes/dashboard.website-analysis'
import { Route as DashboardSimulationRouteImport } from './routes/dashboard.simulation'
import { Route as DashboardReputationRouteImport } from './routes/dashboard.reputation'
import { Route as DashboardIntelligenceRouteImport } from './routes/dashboard.intelligence'
import { Route as DashboardInfluencersRouteImport } from './routes/dashboard.influencers'
import { Route as DashboardCrmRouteImport } from './routes/dashboard.crm'
import { Route as DashboardCreativeRouteImport } from './routes/dashboard.creative'
import { Route as DashboardCollaborationRouteImport } from './routes/dashboard.collaboration'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as DashboardBrandGuidelineRouteImport } from './routes/dashboard.brand-guideline'
import { Route as DashboardBrandDnaSetupRouteImport } from './routes/dashboard.brand-dna-setup'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAudienceRouteImport } from './routes/dashboard.audience'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardCreativeTemplatesRouteImport } from './routes/dashboard.creative.templates'
import { Route as ApiPublicHooksGa4SyncRouteImport } from './routes/api/public/hooks/ga4-sync'
import { Route as DashboardCreativeTemplatesEditorTemplateIdRouteImport } from './routes/dashboard.creative.templates.editor.$templateId'
import { Route as ApiPublicGaOauthCallbackRouteImport } from './routes/api/public/ga/oauth/callback'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebsiteAnalysisRoute =
  DashboardWebsiteAnalysisRouteImport.update({
    id: '/website-analysis',
    path: '/website-analysis',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSimulationRoute = DashboardSimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReputationRoute = DashboardReputationRouteImport.update({
  id: '/reputation',
  path: '/reputation',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntelligenceRoute = DashboardIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfluencersRoute = DashboardInfluencersRouteImport.update({
  id: '/influencers',
  path: '/influencers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCrmRoute = DashboardCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCreativeRoute = DashboardCreativeRouteImport.update({
  id: '/creative',
  path: '/creative',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCollaborationRoute = DashboardCollaborationRouteImport.update({
  id: '/collaboration',
  path: '/collaboration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandGuidelineRoute = DashboardBrandGuidelineRouteImport.update({
  id: '/brand-guideline',
  path: '/brand-guideline',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBrandDnaSetupRoute = DashboardBrandDnaSetupRouteImport.update({
  id: '/brand-dna-setup',
  path: '/brand-dna-setup',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAudienceRoute = DashboardAudienceRouteImport.update({
  id: '/audience',
  path: '/audience',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreativeTemplatesRoute =
  DashboardCreativeTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => DashboardCreativeRoute,
  } as any)
const ApiPublicHooksGa4SyncRoute = ApiPublicHooksGa4SyncRouteImport.update({
  id: '/api/public/hooks/ga4-sync',
  path: '/api/public/hooks/ga4-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCreativeTemplatesEditorTemplateIdRoute =
  DashboardCreativeTemplatesEditorTemplateIdRouteImport.update({
    id: '/editor/$templateId',
    path: '/editor/$templateId',
    getParentRoute: () => DashboardCreativeTemplatesRoute,
  } as any)
const ApiPublicGaOauthCallbackRoute =
  ApiPublicGaOauthCallbackRouteImport.update({
    id: '/api/public/ga/oauth/callback',
    path: '/api/public/ga/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/brand-dna-setup': typeof DashboardBrandDnaSetupRoute
  '/dashboard/brand-guideline': typeof DashboardBrandGuidelineRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/collaboration': typeof DashboardCollaborationRoute
  '/dashboard/creative': typeof DashboardCreativeRouteWithChildren
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/reputation': typeof DashboardReputationRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/website-analysis': typeof DashboardWebsiteAnalysisRoute
  '/dashboard/creative/templates': typeof DashboardCreativeTemplatesRouteWithChildren
  '/api/public/hooks/ga4-sync': typeof ApiPublicHooksGa4SyncRoute
  '/api/public/ga/oauth/callback': typeof ApiPublicGaOauthCallbackRoute
  '/dashboard/creative/templates/editor/$templateId': typeof DashboardCreativeTemplatesEditorTemplateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/brand-dna-setup': typeof DashboardBrandDnaSetupRoute
  '/dashboard/brand-guideline': typeof DashboardBrandGuidelineRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/collaboration': typeof DashboardCollaborationRoute
  '/dashboard/creative': typeof DashboardCreativeRouteWithChildren
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/reputation': typeof DashboardReputationRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/website-analysis': typeof DashboardWebsiteAnalysisRoute
  '/dashboard/creative/templates': typeof DashboardCreativeTemplatesRouteWithChildren
  '/api/public/hooks/ga4-sync': typeof ApiPublicHooksGa4SyncRoute
  '/api/public/ga/oauth/callback': typeof ApiPublicGaOauthCallbackRoute
  '/dashboard/creative/templates/editor/$templateId': typeof DashboardCreativeTemplatesEditorTemplateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/api/chat': typeof ApiChatRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/audience': typeof DashboardAudienceRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/brand-dna-setup': typeof DashboardBrandDnaSetupRoute
  '/dashboard/brand-guideline': typeof DashboardBrandGuidelineRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/collaboration': typeof DashboardCollaborationRoute
  '/dashboard/creative': typeof DashboardCreativeRouteWithChildren
  '/dashboard/crm': typeof DashboardCrmRoute
  '/dashboard/influencers': typeof DashboardInfluencersRoute
  '/dashboard/intelligence': typeof DashboardIntelligenceRoute
  '/dashboard/reputation': typeof DashboardReputationRoute
  '/dashboard/simulation': typeof DashboardSimulationRoute
  '/dashboard/website-analysis': typeof DashboardWebsiteAnalysisRoute
  '/dashboard/creative/templates': typeof DashboardCreativeTemplatesRouteWithChildren
  '/api/public/hooks/ga4-sync': typeof ApiPublicHooksGa4SyncRoute
  '/api/public/ga/oauth/callback': typeof ApiPublicGaOauthCallbackRoute
  '/dashboard/creative/templates/editor/$templateId': typeof DashboardCreativeTemplatesEditorTemplateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/api/chat'
    | '/auth/callback'
    | '/dashboard/analytics'
    | '/dashboard/audience'
    | '/dashboard/billing'
    | '/dashboard/brand-dna-setup'
    | '/dashboard/brand-guideline'
    | '/dashboard/campaigns'
    | '/dashboard/collaboration'
    | '/dashboard/creative'
    | '/dashboard/crm'
    | '/dashboard/influencers'
    | '/dashboard/intelligence'
    | '/dashboard/reputation'
    | '/dashboard/simulation'
    | '/dashboard/website-analysis'
    | '/dashboard/creative/templates'
    | '/api/public/hooks/ga4-sync'
    | '/api/public/ga/oauth/callback'
    | '/dashboard/creative/templates/editor/$templateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/api/chat'
    | '/auth/callback'
    | '/dashboard/analytics'
    | '/dashboard/audience'
    | '/dashboard/billing'
    | '/dashboard/brand-dna-setup'
    | '/dashboard/brand-guideline'
    | '/dashboard/campaigns'
    | '/dashboard/collaboration'
    | '/dashboard/creative'
    | '/dashboard/crm'
    | '/dashboard/influencers'
    | '/dashboard/intelligence'
    | '/dashboard/reputation'
    | '/dashboard/simulation'
    | '/dashboard/website-analysis'
    | '/dashboard/creative/templates'
    | '/api/public/hooks/ga4-sync'
    | '/api/public/ga/oauth/callback'
    | '/dashboard/creative/templates/editor/$templateId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/privacy'
    | '/api/chat'
    | '/auth/callback'
    | '/dashboard/analytics'
    | '/dashboard/audience'
    | '/dashboard/billing'
    | '/dashboard/brand-dna-setup'
    | '/dashboard/brand-guideline'
    | '/dashboard/campaigns'
    | '/dashboard/collaboration'
    | '/dashboard/creative'
    | '/dashboard/crm'
    | '/dashboard/influencers'
    | '/dashboard/intelligence'
    | '/dashboard/reputation'
    | '/dashboard/simulation'
    | '/dashboard/website-analysis'
    | '/dashboard/creative/templates'
    | '/api/public/hooks/ga4-sync'
    | '/api/public/ga/oauth/callback'
    | '/dashboard/creative/templates/editor/$templateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  ApiChatRoute: typeof ApiChatRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicHooksGa4SyncRoute: typeof ApiPublicHooksGa4SyncRoute
  ApiPublicGaOauthCallbackRoute: typeof ApiPublicGaOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/website-analysis': {
      id: '/dashboard/website-analysis'
      path: '/website-analysis'
      fullPath: '/dashboard/website-analysis'
      preLoaderRoute: typeof DashboardWebsiteAnalysisRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/simulation': {
      id: '/dashboard/simulation'
      path: '/simulation'
      fullPath: '/dashboard/simulation'
      preLoaderRoute: typeof DashboardSimulationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reputation': {
      id: '/dashboard/reputation'
      path: '/reputation'
      fullPath: '/dashboard/reputation'
      preLoaderRoute: typeof DashboardReputationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/intelligence': {
      id: '/dashboard/intelligence'
      path: '/intelligence'
      fullPath: '/dashboard/intelligence'
      preLoaderRoute: typeof DashboardIntelligenceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/influencers': {
      id: '/dashboard/influencers'
      path: '/influencers'
      fullPath: '/dashboard/influencers'
      preLoaderRoute: typeof DashboardInfluencersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/crm': {
      id: '/dashboard/crm'
      path: '/crm'
      fullPath: '/dashboard/crm'
      preLoaderRoute: typeof DashboardCrmRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/creative': {
      id: '/dashboard/creative'
      path: '/creative'
      fullPath: '/dashboard/creative'
      preLoaderRoute: typeof DashboardCreativeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/collaboration': {
      id: '/dashboard/collaboration'
      path: '/collaboration'
      fullPath: '/dashboard/collaboration'
      preLoaderRoute: typeof DashboardCollaborationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brand-guideline': {
      id: '/dashboard/brand-guideline'
      path: '/brand-guideline'
      fullPath: '/dashboard/brand-guideline'
      preLoaderRoute: typeof DashboardBrandGuidelineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/brand-dna-setup': {
      id: '/dashboard/brand-dna-setup'
      path: '/brand-dna-setup'
      fullPath: '/dashboard/brand-dna-setup'
      preLoaderRoute: typeof DashboardBrandDnaSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audience': {
      id: '/dashboard/audience'
      path: '/audience'
      fullPath: '/dashboard/audience'
      preLoaderRoute: typeof DashboardAudienceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creative/templates': {
      id: '/dashboard/creative/templates'
      path: '/templates'
      fullPath: '/dashboard/creative/templates'
      preLoaderRoute: typeof DashboardCreativeTemplatesRouteImport
      parentRoute: typeof DashboardCreativeRoute
    }
    '/api/public/hooks/ga4-sync': {
      id: '/api/public/hooks/ga4-sync'
      path: '/api/public/hooks/ga4-sync'
      fullPath: '/api/public/hooks/ga4-sync'
      preLoaderRoute: typeof ApiPublicHooksGa4SyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/creative/templates/editor/$templateId': {
      id: '/dashboard/creative/templates/editor/$templateId'
      path: '/editor/$templateId'
      fullPath: '/dashboard/creative/templates/editor/$templateId'
      preLoaderRoute: typeof DashboardCreativeTemplatesEditorTemplateIdRouteImport
      parentRoute: typeof DashboardCreativeTemplatesRoute
    }
    '/api/public/ga/oauth/callback': {
      id: '/api/public/ga/oauth/callback'
      path: '/api/public/ga/oauth/callback'
      fullPath: '/api/public/ga/oauth/callback'
      preLoaderRoute: typeof ApiPublicGaOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardCreativeTemplatesRouteChildren {
  DashboardCreativeTemplatesEditorTemplateIdRoute: typeof DashboardCreativeTemplatesEditorTemplateIdRoute
}

const DashboardCreativeTemplatesRouteChildren: DashboardCreativeTemplatesRouteChildren =
  {
    DashboardCreativeTemplatesEditorTemplateIdRoute:
      DashboardCreativeTemplatesEditorTemplateIdRoute,
  }

const DashboardCreativeTemplatesRouteWithChildren =
  DashboardCreativeTemplatesRoute._addFileChildren(
    DashboardCreativeTemplatesRouteChildren,
  )

interface DashboardCreativeRouteChildren {
  DashboardCreativeTemplatesRoute: typeof DashboardCreativeTemplatesRouteWithChildren
}

const DashboardCreativeRouteChildren: DashboardCreativeRouteChildren = {
  DashboardCreativeTemplatesRoute: DashboardCreativeTemplatesRouteWithChildren,
}

const DashboardCreativeRouteWithChildren =
  DashboardCreativeRoute._addFileChildren(DashboardCreativeRouteChildren)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardAudienceRoute: typeof DashboardAudienceRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardBrandDnaSetupRoute: typeof DashboardBrandDnaSetupRoute
  DashboardBrandGuidelineRoute: typeof DashboardBrandGuidelineRoute
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardCollaborationRoute: typeof DashboardCollaborationRoute
  DashboardCreativeRoute: typeof DashboardCreativeRouteWithChildren
  DashboardCrmRoute: typeof DashboardCrmRoute
  DashboardInfluencersRoute: typeof DashboardInfluencersRoute
  DashboardIntelligenceRoute: typeof DashboardIntelligenceRoute
  DashboardReputationRoute: typeof DashboardReputationRoute
  DashboardSimulationRoute: typeof DashboardSimulationRoute
  DashboardWebsiteAnalysisRoute: typeof DashboardWebsiteAnalysisRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardAudienceRoute: DashboardAudienceRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardBrandDnaSetupRoute: DashboardBrandDnaSetupRoute,
  DashboardBrandGuidelineRoute: DashboardBrandGuidelineRoute,
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardCollaborationRoute: DashboardCollaborationRoute,
  DashboardCreativeRoute: DashboardCreativeRouteWithChildren,
  DashboardCrmRoute: DashboardCrmRoute,
  DashboardInfluencersRoute: DashboardInfluencersRoute,
  DashboardIntelligenceRoute: DashboardIntelligenceRoute,
  DashboardReputationRoute: DashboardReputationRoute,
  DashboardSimulationRoute: DashboardSimulationRoute,
  DashboardWebsiteAnalysisRoute: DashboardWebsiteAnalysisRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  ApiChatRoute: ApiChatRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicHooksGa4SyncRoute: ApiPublicHooksGa4SyncRoute,
  ApiPublicGaOauthCallbackRoute: ApiPublicGaOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
